########## build ##########
FROM node:22-alpine AS build

WORKDIR /app

ARG NPM_REGISTRY=https://mirror2.chabokan.net/npm/
ENV NPM_CONFIG_REGISTRY=${NPM_REGISTRY}

ARG VITE_API_BASE=https://api.adlgasht.com
ENV VITE_API_BASE=${VITE_API_BASE}

COPY package.json package-lock.json* ./

RUN npm install

COPY . .

RUN npm run build


########## final ##########
FROM node:22-alpine AS final

WORKDIR /app

ARG NPM_REGISTRY=https://mirror2.chabokan.net/npm/
ENV NPM_CONFIG_REGISTRY=${NPM_REGISTRY}

RUN npm install -g serve

COPY --from=build /app/dist ./dist

EXPOSE 3698

CMD ["serve", "-s", "dist", "-l", "3698"]
